"""Deterministic settlement policy engine (FR-006, SPECS S-006).

THE CORE RULE: the LLM proposes *which* alternative + rationale; this deterministic
engine decides (auto <= cap / human > cap), builds the exact Atlas call body from
structured state-thread data (NEVER free-form LLM content), re-reads live state
immediately before any write, asserts the real post-state, and writes the
decision-learning record (FR-007).

Cures for the three agent-loop failures (doc/PRD.md §1):
- infinite loop -> the orchestrator's step budget + explicit give_up (orchestrator.py).
- stale data    -> :class:`StaleStateError` below (re-read before write).
- false success -> :class:`FalseSuccessError` below (assert post-state, not HTTP 200).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone

from tripcascade.agent.config import Settings, get_settings
from tripcascade.agent.decision_log import DecisionLog
from tripcascade.atlas_tools.client import AtlasClient
from tripcascade.graph.models import (
    ActionType,
    AtlasEntityRef,
    DecisionRecord,
    DecisionStatus,
    Node,
    Offer,
    Outcome,
    ReplanProposal,
    SettlementDecision,
)

logger = logging.getLogger(__name__)


class StaleStateError(Exception):
    """Raised when live state changed between proposal and write (re-read guard)."""


class FalseSuccessError(Exception):
    """Raised when a call returns 200/ok but the post-state is empty (false success)."""


@dataclass
class AtlasResult:
    """Outcome of a policy-executed Atlas write (asserted post-state)."""

    success: bool = False
    orderNo: str | None = None
    payment_confirmation_id: str | None = None
    ticket_status: str = ""
    ticket_numbers: list[str] = field(default_factory=list)
    asserted: bool = False  # True only after post-state verified non-empty
    record: DecisionRecord | None = None
    raw: dict = field(default_factory=dict)


class PolicyEngine:
    """Bounded-autonomy settlement: auto <= cap + audit log; human approval > cap.

    Deterministic code only. The LLM never constructs the Atlas call body
    (skills/human_checkpoint_rules.md §3.1). The cap is read from settings,
    never generated by the LLM (default 5000 cents = S$50, doc/PRD.md §6).
    """

    def __init__(
        self,
        settings: Settings | None = None,
        client: AtlasClient | None = None,
        decision_log: DecisionLog | None = None,
    ) -> None:
        self.settings = settings or get_settings()
        self.client = client  # may be None for pure evaluate_settlement (no writes)
        self.log = decision_log or DecisionLog()

    # ------------------------------------------------------------------
    # Evaluate (pure decision: auto vs human vs advisory)
    # ------------------------------------------------------------------

    def evaluate_settlement(
        self,
        node: Node,
        proposal: ReplanProposal,
        chosen_offer: Offer | None = None,
    ) -> SettlementDecision:
        """Decide auto-settle (<= cap) vs human-gate (> cap) vs advisory.

        Pure: no Atlas call. The orchestrator calls this after the LLM proposes.
        """
        decision_id = f"dec_{node.node_id}_{datetime.now(timezone.utc).strftime('%H%M%S%f')}"
        amount = int(proposal.fare_difference_cents)
        cap = int(self.settings.settlement_cap_cents)

        # Advisory node (hotel/activity/transfer) -> no Atlas write, ever.
        if not node.actionable:
            return SettlementDecision(
                decision_id=decision_id,
                node_id=node.node_id,
                action=ActionType.NOTIFY,
                amount_cents=0,
                cap_cents=cap,
                auto_settle=False,
                held=False,
                advisory=True,
                reasoning_trace=proposal.rationale or "advisory node — impact analysis + drafted notification",
                model_tier_used=proposal.model_tier_used,
                status=DecisionStatus.ADVISORY,
            )

        auto = amount <= cap
        new_fare_cents = (
            int(round(chosen_offer.total_price * 100)) if chosen_offer and chosen_offer.total_price else None
        )
        original_fare_cents = (
            int(round(node.total_price * 100)) if node.total_price is not None else None
        )
        return SettlementDecision(
            decision_id=decision_id,
            node_id=node.node_id,
            action=ActionType.RE_BOOK,
            amount_cents=amount,
            cap_cents=cap,
            auto_settle=auto,
            held=not auto,
            advisory=False,
            reasoning_trace=proposal.rationale,
            model_tier_used=proposal.model_tier_used,
            chosen_offer_id=proposal.chosen_offer_id,
            original_fare_cents=original_fare_cents,
            new_fare_cents=new_fare_cents,
            status=DecisionStatus.PROPOSED,
        )

    # ------------------------------------------------------------------
    # Build the Atlas call body (deterministic; NEVER LLM)
    # ------------------------------------------------------------------

    def build_atlas_call_body(
        self, decision: SettlementDecision, node: Node, proposal: ReplanProposal
    ) -> dict:
        """Construct the exact Atlas call from structured state-thread data.

        The LLM never builds this. Source: offer_id/orderNo/amount_cents/passengers.
        (skills/human_checkpoint_rules.md §3.1, doc/SPECS.md §7.)
        """
        ref: AtlasEntityRef | None = node.atlas_entity_ref
        return {
            "intent": "re_book",
            "chosen_offer_id": decision.chosen_offer_id,
            "original_orderNo": ref.orderNo if ref else None,
            "amount_cents": decision.amount_cents,
            "cap_cents": decision.cap_cents,
            "passengers": list(node.passengers),
            "reasoning_trace": proposal.rationale,  # for the audit trail only
        }

    # ------------------------------------------------------------------
    # Execute (auto-settle path: <= cap)
    # ------------------------------------------------------------------

    def _run_pipeline(
        self,
        decision: SettlementDecision,
        node: Node,
        proposal: ReplanProposal,
    ) -> tuple:
        """Re-read + build + order + pay + status, with NO record write.

        Shared by :meth:`execute` (auto) and :meth:`execute_approved` (human).
        Each caller writes exactly ONE decision record with the right outcome.
        """
        if decision.advisory:
            raise ValueError("advisory decisions are not executed via Atlas; use draft_notification")
        if decision.held:
            raise ValueError("above-cap decisions require execute_approved(human_verdict)")
        if self.client is None:
            raise RuntimeError("policy engine has no Atlas client; cannot execute")
        assert decision.auto_settle, "pipeline is for auto/approved decisions only"

        # 1. re-read live state before any write
        self._assert_live_state_unchanged(decision, node)

        # 2. build the call body (policy engine, never LLM)
        body = self.build_atlas_call_body(decision, node, proposal)

        # 3. order create (Commitment)
        verify = self.client.verify(decision.chosen_offer_id)
        order = self.client.order_create(verify.booking_id or "", body["passengers"])
        if not order.orderNo:
            raise FalseSuccessError("order create returned ok but orderNo is empty")

        # 4. order pay (Money) -> assert confirmation_id
        pay = self.client.order_pay(order.payment_confirmation_id or "")
        if not pay.success or not pay.payment_confirmation_id:
            raise FalseSuccessError("order pay returned ok but no payment_confirmation_id")

        # 5. order status (Aftercare query) -> assert post-state
        status = self.client.order_status(order.orderNo)
        return order, pay, status

    def execute(
        self,
        decision: SettlementDecision,
        node: Node,
        proposal: ReplanProposal,
    ) -> AtlasResult:
        """Auto-execute an at-or-below-cap settlement; writes ONE auto_settled record."""
        order, pay, status = self._run_pipeline(decision, node, proposal)
        rec = self._record(
            decision=decision,
            outcome=Outcome.AUTO_SETTLED,
            human_verdict=None,
            order_no=order.orderNo,
            pay_conf=pay.payment_confirmation_id,
        )
        decision.status = DecisionStatus.AUTO_EXECUTED
        return AtlasResult(
            success=True,
            orderNo=order.orderNo,
            payment_confirmation_id=pay.payment_confirmation_id,
            ticket_status=status.ticket_status,
            ticket_numbers=status.ticket_numbers,
            asserted=True,
            record=rec,
        )

    # ------------------------------------------------------------------
    # Execute approved (above-cap path: human Approve)
    # ------------------------------------------------------------------

    def execute_approved(
        self,
        decision: SettlementDecision,
        node: Node,
        proposal: ReplanProposal,
        human_verdict: str,
    ) -> AtlasResult:
        """Execute an above-cap settlement after explicit human approval.

        Same re-read + assert pipeline as :meth:`execute`; the only difference is
        the recorded outcome (HUMAN_APPROVED) + the human verdict text.
        """
        if not decision.held:
            raise ValueError("execute_approved is for above-cap (held) decisions only")
        # mark as auto now that a human approved; re-use the pipeline
        decision.auto_settle = True
        decision.held = False
        order, pay, status = self._run_pipeline(decision, node, proposal)
        rec = self._record(
            decision=decision,
            outcome=Outcome.HUMAN_APPROVED,
            human_verdict=human_verdict,
            order_no=order.orderNo,
            pay_conf=pay.payment_confirmation_id,
        )
        decision.status = DecisionStatus.EXECUTED
        return AtlasResult(
            success=True,
            orderNo=order.orderNo,
            payment_confirmation_id=pay.payment_confirmation_id,
            ticket_status=status.ticket_status,
            ticket_numbers=status.ticket_numbers,
            asserted=True,
            record=rec,
        )

    def reject(
        self, decision: SettlementDecision, human_verdict: str
    ) -> DecisionRecord:
        """Record a human rejection (above-cap). No Atlas write."""
        decision.status = DecisionStatus.REJECTED
        rec = self._record(
            decision=decision,
            outcome=Outcome.HUMAN_REJECTED,
            human_verdict=human_verdict,
            order_no=None,
            pay_conf=None,
        )
        return rec

    # ------------------------------------------------------------------
    # Advisory: draft a notification (never an Atlas booking)
    # ------------------------------------------------------------------

    def draft_notification(self, node: Node, impact: str) -> str:
        """Deterministic notification template for advisory nodes.

        In production a routine-tier LLM refines this; the policy engine provides
        the structured template so the content is never free-form LLM-only.
        (skills/human_checkpoint_rules.md §2, doc/atlas_surface.md §4.)
        """
        return (
            f"Subject: Possible late/missed arrival for {node.node_id}\n"
            f"Impact: {impact}\n"
            f"Node type: {node.node_type.value} (advisory — no Atlas booking action).\n"
            f"Please review your {node.location_destination or 'destination'} arrangements "
            f"for {node.scheduled_start.date()}."
        )

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _assert_live_state_unchanged(
        self, decision: SettlementDecision, node: Node
    ) -> None:
        """Re-read the world before writing; raise StaleStateError on drift."""
        if self.client is None or decision.chosen_offer_id is None:
            return
        # re-verify the chosen offer -> price may have changed (priceChange array)
        verify = self.client.verify(decision.chosen_offer_id)
        if decision.new_fare_cents is not None and verify.total_price is not None:
            live_cents = int(round(verify.total_price * 100))
            if live_cents != decision.new_fare_cents:
                raise StaleStateError(
                    f"fare changed between proposal ({decision.new_fare_cents}c) and "
                    f"execution ({live_cents}c); re-plan required"
                )
        # if the node already has an order, confirm it is unpaid (no double-pay)
        ref = node.atlas_entity_ref
        if ref and ref.orderNo:
            st = self.client.order_status(ref.orderNo)
            if st.paid:
                raise StaleStateError(
                    f"order {ref.orderNo} is already paid; double-pay prevented"
                )

    def _record(
        self,
        decision: SettlementDecision,
        outcome: Outcome,
        human_verdict: str | None,
        order_no: str | None,
        pay_conf: str | None,
    ) -> DecisionRecord:
        rec = DecisionRecord(
            record_id=DecisionLog.new_record_id(),
            timestamp=DecisionLog.now_iso(),
            node_id=decision.node_id,
            action=decision.action,
            amount_cents=decision.amount_cents,
            cap_cents=decision.cap_cents,
            outcome=outcome,
            human_verdict=human_verdict,
            reasoning_trace=decision.reasoning_trace,
            model_tier_used=decision.model_tier_used,
            atlas_state_refs={
                "orderNo": order_no,
                "payment_confirmation_id": pay_conf,
            },
            reusable=True,
        )
        self.log.append(rec)
        return rec
